# Neural Network

In [15]:
from ucimlrepo import fetch_ucirepo
from sklearn.preprocessing import LabelEncoder
import numpy as np
import matplotlib.pyplot as plt
import copy
import math
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

%matplotlib inline

2023-10-03 17:33:14.229238: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


# Preparing the data

In [ ]:
# fetch dataset 
iris = fetch_ucirepo(id=53)

In [ ]:
# data (as pandas dataframes) 
X = iris.data.features
y = iris.data.targets

In [ ]:
le = LabelEncoder()
label = le.fit_transform(y['class'])

In [ ]:
y.drop('class', axis=1, inplace=True)

In [ ]:
y['class'] = label

In [ ]:
X_np = X.to_numpy()
y_np = y.to_numpy()

## Tensorflow Approach

In [16]:
y_np = y_np.reshape(150, 1)

In [20]:
model = Sequential(
    [
        Input(shape=(4,)),
        Dense(25, activation="relu"),
        Dense(15, activation="relu"),
        Dense(3, activation="linear")
    ]
)       

In [21]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 25)                125       
                                                                 
 dense_4 (Dense)             (None, 15)                390       
                                                                 
 dense_5 (Dense)             (None, 3)                 48        
                                                                 
Total params: 563
Trainable params: 563
Non-trainable params: 0
_________________________________________________________________


In [22]:
[layer1, layer2, layer3] = model.layers

In [23]:
W1, b1 = layer1.get_weights()
W2, b2 = layer2.get_weights()
W3, b3 = layer3.get_weights()

print(f'W1: {W1.shape}, b1: {b1.shape}')
print(f'W2: {W2.shape}, b2: {b2.shape}')
print(f'W3: {W3.shape}, b3: {b3.shape}')

W1: (4, 25), b1: (25,)
W2: (25, 15), b2: (15,)
W3: (15, 3), b3: (3,)


In [24]:
print(model.layers[2].weights)

[<tf.Variable 'dense_5/kernel:0' shape=(15, 3) dtype=float32, numpy=
array([[ 3.5025209e-01,  5.3345692e-01, -1.2304914e-01],
       [-5.4766965e-01,  4.6755350e-01,  5.6372344e-02],
       [-4.9092826e-01, -3.4757918e-01, -4.7534645e-02],
       [-1.1339265e-01, -1.3634333e-01, -4.8860830e-01],
       [ 8.0035686e-02,  2.4624860e-01,  2.5517941e-03],
       [ 2.3115611e-01,  4.1840404e-01,  2.3897886e-02],
       [ 2.6185948e-01, -7.8607827e-02, -3.5077500e-01],
       [-2.5193772e-01, -1.4884785e-01,  2.9311270e-01],
       [-2.7430505e-01,  5.5891216e-01,  3.5259724e-01],
       [-3.0743918e-01,  5.1406217e-01,  3.1440884e-01],
       [ 1.4187127e-01, -2.4572855e-01, -4.3074363e-01],
       [ 3.7771773e-01,  3.1418735e-01,  2.3910946e-01],
       [-1.8654138e-01,  4.6636045e-02,  3.9942116e-01],
       [ 1.5757012e-01,  4.8735011e-01, -4.2487520e-01],
       [-6.3694000e-02,  4.4483399e-01, -1.8817186e-04]], dtype=float32)>, <tf.Variable 'dense_5/bias:0' shape=(3,) dtype=float32, nu

In [26]:
model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=tf.keras.optimizers.Adam(0.001),
)

model.fit(
    X_np,y_np,
    epochs=100
)

Epoch 1/100
5/5 [==============================] - 1s 3ms/step - loss: 0.6444
Epoch 2/100
5/5 [==============================] - 0s 3ms/step - loss: 0.6227
Epoch 3/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6050
Epoch 4/100
5/5 [==============================] - 0s 4ms/step - loss: 0.5867
Epoch 5/100
5/5 [==============================] - 0s 3ms/step - loss: 0.5684
Epoch 6/100
5/5 [==============================] - 0s 4ms/step - loss: 0.5517
Epoch 7/100
5/5 [==============================] - 0s 5ms/step - loss: 0.5363
Epoch 8/100
5/5 [==============================] - 0s 3ms/step - loss: 0.5211
Epoch 9/100
5/5 [==============================] - 0s 3ms/step - loss: 0.5078
Epoch 10/100
5/5 [==============================] - 0s 4ms/step - loss: 0.4946
Epoch 11/100
5/5 [==============================] - 0s 5ms/step - loss: 0.4819
Epoch 12/100
5/5 [==============================] - 0s 4ms/step - loss: 0.4702
Epoch 13/100
5/5 [==============================] - 0s 4ms/st

In [113]:
X_np[0].reshape(1, 4)

array([[5.1, 3.5, 1.4, 0.2]])

In [27]:
prediction = model.predict(X_np[149].reshape(1, 4))
print(f" predicting second type: {prediction}")

1/1 [==============================] - 0s 186ms/step
 predicting second type: [[-6.902088   1.9760375  3.8679729]]


In [29]:
prediction_p = tf.nn.softmax(prediction)

In [30]:
y_np[149]

array([2])

In [33]:
print(f" predicting a Two. Probability vector: \n{prediction_p}")
print(f"Total of predictions: {np.sum(prediction_p):0.3f}")

 predicting a Two. Probability vector: 
[[1.8265082e-05 1.3102156e-01 8.6896020e-01]]
Total of predictions: 1.000


In [34]:
yhat = np.argmax(prediction_p)
print(f"np.argmax(prediction_p): {yhat}")

np.argmax(prediction_p): 2


## Evaluating

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
x_train, x_, y_train, y_ = train_test_split(X_np, y_np, test_size=0.40, random_state=42)

In [37]:
x_cv, x_test, y_cv, y_test = train_test_split(x_, y_, test_size=0.50, random_state=42)

In [38]:
del x_, y_

In [39]:
print(f"the shape of the training set (input) is: {x_train.shape}")
print(f"the shape of the training set (target) is: {y_train.shape}\n")
print(f"the shape of the cross validation set (input) is: {x_cv.shape}")
print(f"the shape of the cross validation set (target) is: {y_cv.shape}\n")
print(f"the shape of the test set (input) is: {x_test.shape}")
print(f"the shape of the test set (target) is: {y_test.shape}")

the shape of the training set (input) is: (90, 4)
the shape of the training set (target) is: (90, 1)

the shape of the cross validation set (input) is: (30, 4)
the shape of the cross validation set (target) is: (30, 1)

the shape of the test set (input) is: (30, 4)
the shape of the test set (target) is: (30, 1)


## Test different models

In [42]:
def build_models():
    
    tf.random.set_seed(20)
    
    model_1 = Sequential(
        [
            Dense(25, activation = 'relu'),
            Dense(15, activation = 'relu'),
            Dense(3, activation = 'linear')
        ],
        name='model_1'
    )

    model_2 = Sequential(
        [
            Dense(20, activation = 'relu'),
            Dense(12, activation = 'relu'),
            Dense(12, activation = 'relu'),
            Dense(20, activation = 'relu'),
            Dense(3, activation = 'linear')
        ],
        name='model_2'
    )

    model_3 = Sequential(
        [
            Dense(32, activation = 'relu'),
            Dense(16, activation = 'relu'),
            Dense(8, activation = 'relu'),
            Dense(4, activation = 'relu'),
            Dense(12, activation = 'relu'),
            Dense(3, activation = 'linear')
        ],
        name='model_3'
    )
    
    model_list = [model_1, model_2, model_3]
    
    return model_list

In [45]:
from sklearn.metrics import mean_squared_error

In [51]:
y_train[:5]

array([[2],
       [0],
       [0],
       [0],
       [1]])

In [49]:
yhat = model.predict(x_train)

3/3 [==============================] - 0s 3ms/step


In [58]:
yhatt = np.array([[np.argmax(i)] for i in yhat[:5]])

In [60]:
yhatt[:5].shape

(5, 1)

In [66]:
y_cv.shape

(30, 1)

In [75]:
# Initialize lists that will contain the errors for each model
nn_train_mses = []
nn_cv_mses = []

# Build the models
nn_models = build_models()

# Loop over the the models
for model in nn_models:
    
    # Setup the loss and optimizer
    model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=tf.keras.optimizers.Adam(0.001),
    )

    print(f"Training {model.name}...")
    
    # Train the model
    model.fit(
        x_train, y_train,
        epochs=50,
        verbose=0
    )
    
    print("Done!\n")

    
    # Record the training MSEs
    yhat = model.predict(x_train)
    yhat = np.array([[np.argmax(i)] for i in yhat])
    train_mse = mean_squared_error(y_train, yhat) / 2
    nn_train_mses.append(train_mse)
    
    # Record the cross validation MSEs 
    yhat = model.predict(x_cv)
    yhat = np.array([[np.argmax(i)] for i in yhat])
    cv_mse = mean_squared_error(y_cv, yhat) / 2
    nn_cv_mses.append(cv_mse)

    
# print results
print("RESULTS:")
for model_num in range(len(nn_train_mses)):
    print(
        f"Model {model_num+1}: Training MSE: {nn_train_mses[model_num]:.2f}, " +
        f"CV MSE: {nn_cv_mses[model_num]:.8f}"
        )

Training model_1...
Done!

1/1 [==============================] - 0s 21ms/step
Training model_2...
Done!

1/1 [==============================] - 0s 26ms/step
Training model_3...
Done!

1/1 [==============================] - 0s 22ms/step
RESULTS:
Model 1: Training MSE: 0.03, CV MSE: 0.00000000
Model 2: Training MSE: 0.02, CV MSE: 0.00000000
Model 3: Training MSE: 0.17, CV MSE: 0.10000000


In [80]:
# Select the model with the lowest CV MSE
model_num = 2

# Compute the test MSE
yhat = nn_models[model_num-1].predict(x_test)
yhat = np.array([[np.argmax(i)] for i in yhat])
test_mse = mean_squared_error(y_test, yhat) / 2

print(f"Selected Model: {model_num}")
print(f"Training MSE: {nn_train_mses[model_num-1]:.2f}")
print(f"Cross Validation MSE: {nn_cv_mses[model_num-1]:.2f}")
print(f"Test MSE: {test_mse:.2f}")

1/1 [==============================] - 0s 25ms/step
Selected Model: 2
Training MSE: 0.02
Cross Validation MSE: 0.00
Test MSE: 0.02


In [94]:
test_error = np.mean(yhat != y_test)

In [95]:
test_error

0.03333333333333333

In [96]:
np.where(yhat != y_test)

(array([16]), array([0]))